### PR TITLE
Added support of heredoc/nowdoc.

### PR DESCRIPTION
**Pull request by Daniel-KM**

### CODE REVIEW

**Comment by zerocrates** [comment]
Since you're only `ltrim`-ing, you'll only take off 1-byte characters off the front so I believe `strlen` and `substr` would suffice for taking out the indents?

**Comment by zerocrates** [comment]
My more substantive concern would be what happens with heredocs that have variables in them, so they have T_VARIABLE within them... but I think your pattern matching for just "heredoc start" "one token" "heredoc end" already will just exclude those, which should be fine.... maybe also add a check that the middle token is T_ENCAPSED_AND_WHITESPACE?

**Comment by zerocrates** [comment]
You might also end up with issues with CRLF-line-ending source code (i.e., from Windows users) but maybe not a significant problem to worry about.

**Comment by Daniel-KM** [comment]
Indeed, it didn't manage strings with variables, because they are never used for translation, so the check for the end at start + 2 is enough in that case. A more complex algorithm can be used to extract strings with variables, but it will be useless for the purpose of translation. Have you an example of translated variables in omeka and modules? And, in that case, it should be considered as a first step to support heredoc and a warning in the readme should be enough for now.

For the crlf, there are two points. The last end of line should be removed and it should be the one used in the file, but i didn't tested with windows files, i never see it in the code. I fixed it anyway in a new commit. For the end of line used in a multi-line string, it is kept before and after implode/explode with "\n". It may be cleaned when creating the pot.

I used the trimming to count the number of spaces or the number of tabs in the beginning of each line of the string, but the new commit is smarter with `strspn` and it manages utf8 strings fine.

**Comment by zerocrates** [comment]
Supporting variables within strings isn't a goal here. I was just thinking an extra check to ensure they're rejected as possible matches, as you've done now. I think in practice the end whitespace will mean there's always at least two tokens inside any heredoc with variables, but I think this way is a little more explicit which I like.

`strspn`, looks well-suited to what you're doing. I'd still suggest I think that all your other mb_strpos/mb_substr usages are looking for single-byte characters only, so the `mb_`-less versions should work correctly in those places too, even with UTF-8 strings/code. I think it's preferable to not use mbstring if we don't need it, and we shouldn't need it here: bytewise searching for and even trimming of ASCII characters is safe in UTF-8.

We don't use Windows line-endings but I figure the tool should ideally not fail on their presence, perhaps in a module, or completely outside-Omeka use case or something, so it's good that you're supporting them.

I do have one final suggestion, though, that maybe overrides the others... since you have a tight match of just three tokens in a row, T_HEREDOC_START, T_ENCAPSED_AND_WHITESPACE, T_HEREDOC_END, have you considered just using the same `eval` method being used for regular strings?

```
$heredocStart = $backtrackToken[1];
$heredocBody = $tokens[$backtrackIndex + 1][1];
$heredocEnd = $tokens[$backtrackIndex + 2][1];
$string = eval("return {$heredocStart}{$heredocBody}{$heredocEnd};");
```

Then you should get "for free" newline handling and indentation removal.

**Comment by Daniel-KM** [comment]
Indeed, it's working fine with eval.

**Comment by zerocrates** [comment]
Looks fine to me.

Out of curiosity, where are you looking to use a heredoc/nowdoc as a translatable string? We don't see so many with linebreaks and so on inside typically.

**Comment by Daniel-KM** [comment]
This is for the new module [Two Factor Authentication](https://gitlab.com/Daniel-KM/Omeka-S-module-TwoFactorAuth) (published soon) and other modules where an email should be sent. And it can be used in Omeka for the emails sent for password.

**Pull request merged**
